# Generated by Django 4.1.2 on 2022-11-30 20:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/imgCarrusel')),
            ],
        ),
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('semanal', models.DateField()),
                ('sabatino', models.DateField()),
                ('inscripcion', models.PositiveIntegerField()),
                ('colegiatura', models.PositiveIntegerField()),
                ('pronto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.FileField(default=None, upload_to='static/img/cursos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('costo', models.PositiveIntegerField()),
                ('inicio', models.DateField()),
                ('hora', models.TimeField()),
                ('fin', models.DateField()),
                ('imagen', models.FileField(default=None, upload_to='static/img/expres')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('', ''), ('Robótica', 'Robótica'), ('Herramientas', 'Herramientas'), ('Cables, accesorios e insumos', 'Cables, accesorios e insumos')], default=None, max_length=50)),
                ('imagen', models.FileField(default=None, upload_to='static/img/productos')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('imagen', models.FileField(default=None, upload_to='static/img/modulos')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.curso')),
            ],
        ),
    ]
